version: "3.9"

services:

  mysql-server:
    image: mysql
    network_mode: host
    volumes:
      - mysqldata:${MYSQLDATA}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  adminer:
    image: adminer
    network_mode: host
    depends_on:
      - mysql-server

volumes:
  mysqldata:
    external: true
    name: mysql-data

